import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateInvestorMemo(startupIdea: string, data: any) {
  // Create a new PDF document (A4 portrait)
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  let yPos = margin;

  // Helper functions
  const addPageBreak = () => {
    doc.addPage();
    yPos = margin;
  };

  const addSectionTitle = (title: string) => {
    if (yPos > pageHeight - 40) addPageBreak();
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(title, margin, yPos);
    yPos += 8;
    
    // Draw a subtle line under the title
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
    yPos += 6;
  };

  const addSubSectionTitle = (title: string) => {
    if (yPos > pageHeight - 30) addPageBreak();
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(51, 65, 85);
    doc.text(title, margin, yPos);
    yPos += 6;
  };

  const addText = (text: string, fontSize = 10, isBold = false) => {
    if (!text) return;
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(71, 85, 105);
    
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    
    // Check if we need a page break for the block of text
    if (yPos + (lines.length * 5) > pageHeight - margin) {
      addPageBreak();
    }
    
    doc.text(lines, margin, yPos);
    yPos += lines.length * 5 + 4;
  };

  const addBulletPoints = (items: string[]) => {
    if (!items || items.length === 0) return;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    
    items.forEach(item => {
      const bullet = "• ";
      const lines = doc.splitTextToSize(item, pageWidth - margin * 2 - 5);
      
      if (yPos + (lines.length * 5) > pageHeight - margin) {
        addPageBreak();
      }
      
      doc.text(bullet, margin, yPos);
      doc.text(lines, margin + 5, yPos);
      yPos += lines.length * 5 + 2;
    });
    yPos += 4;
  };

  // --- 1. COVER PAGE ---
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text("Venture Intel", pageWidth / 2, pageHeight / 3, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text("Investor Due Diligence Memo", pageWidth / 2, (pageHeight / 3) + 12, { align: 'center' });

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  
  // Center multiline startup idea
  const ideaLines = doc.splitTextToSize(startupIdea, pageWidth - 40);
  doc.text(ideaLines, pageWidth / 2, (pageHeight / 2), { align: 'center' });

  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${dateStr}`, pageWidth / 2, pageHeight - 40, { align: 'center' });
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Venture Intel", pageWidth / 2, pageHeight - 30, { align: 'center' });

  addPageBreak();

  // --- 2. EXECUTIVE SUMMARY ---
  if (data.report?.executiveSummary) {
    addSectionTitle("Executive Summary");
    addText(data.report.executiveSummary);
    yPos += 6;
  }

  // --- 3. MARKET INTELLIGENCE ---
  if (data.marketResearch) {
    addSectionTitle("Market Intelligence");
    
    if (data.marketResearch.marketSize) {
      addSubSectionTitle("Market Size & Growth");
      addText(data.marketResearch.marketSize);
    }
    
    if (data.marketResearch.targetAudience) {
      addSubSectionTitle("Target Audience");
      addText(data.marketResearch.targetAudience);
    }
    
    if (data.marketResearch.trends && data.marketResearch.trends.length > 0) {
      addSubSectionTitle("Key Trends");
      addBulletPoints(data.marketResearch.trends);
    }
    yPos += 6;
  }

  // --- 4. COMPETITIVE LANDSCAPE ---
  if (data.competitors) {
    addSectionTitle("Competitive Landscape");
    
    if (data.competitors.competitiveAdvantage) {
      addText(data.competitors.competitiveAdvantage);
      yPos += 4;
    }

    const compileCompetitors = (comps: any[], type: string) => {
      return (comps || []).map(c => [
        c.companyName || 'Unknown',
        type,
        c.funding || 'Unknown',
        `${c.similarityScore || 0}%`
      ]);
    };

    const direct = compileCompetitors(data.competitors.directCompetitors, 'Direct');
    const indirect = compileCompetitors(data.competitors.indirectCompetitors, 'Indirect');
    const tableBody = [...direct, ...indirect];

    if (tableBody.length > 0) {
      autoTable(doc, {
        startY: yPos,
        head: [['Company', 'Type', 'Funding', 'Similarity']],
        body: tableBody,
        theme: 'grid',
        headStyles: { fillColor: [30, 41, 59], textColor: 255, fontSize: 10, fontStyle: 'bold' },
        bodyStyles: { fontSize: 9, textColor: 71 },
        margin: { left: margin, right: margin },
      });
      yPos = (doc as any).lastAutoTable.finalY + 14;
    } else {
      addText("No direct or indirect competitors identified.");
    }
  }

  // --- 5. SWOT ANALYSIS ---
  if (data.swot) {
    addSectionTitle("SWOT Analysis");
    
    if (data.swot.swot?.strengths && data.swot.swot.strengths.length > 0) {
      addSubSectionTitle("Strengths");
      addBulletPoints(data.swot.swot.strengths);
    }
    
    if (data.swot.swot?.weaknesses && data.swot.swot.weaknesses.length > 0) {
      addSubSectionTitle("Weaknesses");
      addBulletPoints(data.swot.swot.weaknesses);
    }
    
    if (data.swot.swot?.opportunities && data.swot.swot.opportunities.length > 0) {
      addSubSectionTitle("Opportunities");
      addBulletPoints(data.swot.swot.opportunities);
    }
    
    const combinedThreats = [...(data.swot.swot?.threats || []), ...(data.swot.risks || [])];
    if (combinedThreats.length > 0) {
      addSubSectionTitle("Threats & Risks");
      addBulletPoints(combinedThreats);
    }
  }

  // --- 6. INVESTMENT RECOMMENDATION ---
  if (data.report) {
    addSectionTitle("Investment Recommendation");
    
    if (data.report.recommendation) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      
      // Color-code recommendation
      const rec = data.report.recommendation.toLowerCase();
      if (rec.includes('strong invest')) {
        doc.setTextColor(22, 163, 74); // Green
      } else if (rec.includes('invest')) {
        doc.setTextColor(37, 99, 235); // Blue
      } else if (rec.includes('strong pass')) {
        doc.setTextColor(220, 38, 38); // Red
      } else {
        doc.setTextColor(234, 88, 12); // Orange/Pass
      }
      
      doc.text(`Recommendation: ${data.report.recommendation.toUpperCase()}`, margin, yPos);
      yPos += 10;
    }
    
    if (data.report.keyTakeaways && data.report.keyTakeaways.length > 0) {
      addSubSectionTitle("Key Takeaways");
      addBulletPoints(data.report.keyTakeaways);
    }
  }

  // --- 7. SOURCES APPENDIX ---
  if (data.sources && data.sources.length > 0) {
    addSectionTitle("Sources Appendix");
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    
    data.sources.forEach((source: any, idx: number) => {
      const sourceText = `[${idx + 1}] ${source.title || 'Untitled Source'} - ${source.url}`;
      const lines = doc.splitTextToSize(sourceText, pageWidth - margin * 2);
      
      if (yPos + (lines.length * 4) > pageHeight - margin) {
        addPageBreak();
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 116, 139);
      }
      
      doc.text(lines, margin, yPos);
      yPos += lines.length * 4 + 2;
    });
  }

  // --- ADD FOOTERS TO ALL PAGES ---
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(148, 163, 184);
    
    // Page number
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    
    // Confidential watermark at bottom
    if (i > 1) {
      doc.text("CONFIDENTIAL - Generated by Venture Intel", margin, pageHeight - 10);
    }
  }

  // Trigger file download
  const safeTitle = startupIdea.substring(0, 30).replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`Venture_Intel_Memo_${safeTitle}.pdf`);
}
